
---
- hosts: "{{ list_hosts | default(['fakehost']) }}"
  tasks:
  - name: Copy SSL certs
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
    loop:
    - { src: "../../ssl/makinghopp.com.crt", dest: "/etc/ssl/certs/makinghopp.com.crt", mode: "0644", owner: "prometheus", group: "prometheus" }
    - { src: "../../ssl/makinghopp.com.key", dest: "/etc/ssl/certs/makinghopp.com.key", mode: "0600", owner: "prometheus", group: "prometheus" }
  roles:
  - { role: monitoring/prometheus, tags: ["prometheus-custom"] }    
  - prometheus.prometheus.prometheus
  vars:
    prometheus_global:
      scrape_interval: 60s
      scrape_timeout: 30s
      evaluation_interval: 15s
    prometheus_web_external_url: https://prometheus.makinghopp.com
    prometheus_web_listen_address: "0.0.0.0:9090"
    prometheus_web_config:
      tls_server_config:
        cert_file: "/etc/ssl/certs/makinghopp.com.crt"
        key_file: "/etc/ssl/certs/makinghopp.com.key"
      basic_auth_users:
        monit: $2y$10$RmKp21haSTVnqwtp9QDEruFyBC2zFPi18vvGhHZQ/wo52To9Gbp5.
    prometheus_scrape_configs:
    - job_name: "node"
      scheme: http
      basic_auth:
        username: export
        password: Xevoopo9Ti8Eech5Ma4Aeloghiewaite
      static_configs:
      - targets:
        - localhost:9100
        - "{{ hostvars['homedb'].ansible_host }}:9100"
        - "{{ hostvars['homedb'].ansible_host }}:9187"
        - "{{ hostvars['gitlab'].ansible_host }}:9100"
        - "{{ hostvars['homeweb'].ansible_host }}:9100"
        - "{{ hostvars['clickhouse'].ansible_host }}:9103"
        - "{{ hostvars['head-db-dev'].ansible_host }}:9100"
        - "{{ hostvars['proxy'].ansible_host }}:9100"
        - "{{ hostvars['linux-java'].ansible_host }}:9102"
        - "{{ hostvars['ubuntu-dima'].ansible_host }}:9102"
        - "{{ hostvars['homeprox2'].ansible_host }}:9100"
        - "{{ hostvars['homeprox3'].ansible_host }}:9100"        
      relabel_configs:
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['prometheus'].ansible_host }}:9100"
          replacement: "{{ hostvars['prometheus'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['homeweb'].ansible_host }}:9100"
          replacement: "{{ hostvars['homeweb'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['homedb'].ansible_host }}:9100"
          replacement: "{{ hostvars['homedb'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['homedb'].ansible_host }}:9187"
          replacement: "{{ hostvars['homedb'].inventory_hostname }}"          
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['gitlab'].ansible_host }}:9100"
          replacement: "{{ hostvars['gitlab'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['clickhouse'].ansible_host }}:9103"
          replacement: "{{ hostvars['clickhouse'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['linux-java'].ansible_host }}:9102"
          replacement: "{{ hostvars['linux-java'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['ubuntu-dima'].ansible_host }}:9102"
          replacement: "{{ hostvars['ubuntu-dima'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['head-db-dev'].ansible_host }}:9100"
          replacement: "{{ hostvars['head-db-dev'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['proxy'].ansible_host }}:9100"
          replacement: "{{ hostvars['proxy'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['homeprox2'].ansible_host }}:9100"
          replacement: "{{ hostvars['homeprox2'].inventory_hostname }}"
        - source_labels: [ __address__ ]
          target_label: hostname
          regex: "{{ hostvars['homeprox3'].ansible_host }}:9100"
          replacement: "{{ hostvars['homeprox3'].inventory_hostname }}"
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]  # Look for a HTTP 200 response.
      static_configs:
        - targets:
          - https://makinghopp.com
          - http://provisioning.makinghopp.com:8080
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 127.0.0.1:9115
    prometheus_alertmanager_config:
        - scheme: http
          static_configs:
            - targets: ["127.0.0.1:9093"]
    prometheus_alert_rules:
        - alert: WebReachability
          expr: probe_success == 0
          for: 5m
          labels:
            severity: "critical"
          annotations:
            summary: "{% raw %}{{ $labels.instance }}{% endraw %} is down"

