---

- name: Setup Proxmox gotify notifications
  hosts: "{{ list_hosts | default(['fakehost']) }}"
  roles:
    - { role: proxmox/notifications, tags: ["notifications"] }

- name: Proxmox init setup
  hosts: "{{ list_hosts | default(['fakehost']) }}"
  roles:
    - { role: proxmox/init, tags: ["proxmox-init"] }

- name: Proxmox storage setup
  hosts: "{{ list_hosts | default(['fakehost']) }}"
  roles:
    - { role: proxmox/storage, tags: ["proxmox-storage"] }
