# - name: Include vars
#   ansible.builtin.include_vars: "{{ item }}"
#   with_items:
#     - ../vars/vault.yml
#     - ../vars/main.yml

- name: Install APT packages install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
    - mailutils
    - pwgen
    - atop
    - parted
    - iotop
    - sysstat
    - isc-dhcp-server
    - telnet
    - tcpdump
    - mc
    - vim
    - nvme-cli

- name: Update sysctl config
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: "net.ipv4.ip_forward", value: "1"}
    - { name: "net.ipv6.conf.all.disable_ipv6", value: "1"}
    - { name: "net.ipv6.conf.default.disable_ipv6", value: "1"}

- name: Copy backup mount checker
  ansible.builtin.template:
    src: status_mnt.sh
    dest: /opt/status_mnt.sh
    mode: '0755'

- name: Create checker cron
  ansible.builtin.cron:
    name: "status_mnt.sh"
    minute: "*/60"
    job: "bash /opt/status_mnt.sh >> /tmp/mount.log 2>&1"
    state: present
